In [1]:
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np
print("Import Done!")

Import Done!


In [2]:
df = pd.read_csv("diabetes_prediction_dataset.csv")

In [3]:
x = df.copy()
y = df["diabetes"].copy()

In [4]:
print(x.head())
print(y.head())

   gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0  
0    0
1    0
2    0
3    0
4    0
Name: diabetes, dtype: int64


In [5]:
x["gender"].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [6]:
gender_to_int = {'Male': 0, 'Female': 1, 'Other': 2}
x['gender'] = x['gender'].map(gender_to_int)

In [7]:
x.head(100)

gender   age  hypertension  heart_disease smoking_history    bmi  \
0        1  80.0             0              1           never  25.19   
1        1  54.0             0              0         No Info  27.32   
2        0  28.0             0              0           never  27.32   
3        1  36.0             0              0         current  23.45   
4        0  76.0             1              1         current  20.14   
..     ...   ...           ...            ...             ...    ...   
95       0  19.0             0              0           never  27.32   
96       1  67.0             0              0           never  27.32   
97       0  11.0             0              0         No Info  27.32   
98       1  30.0             0              0         No Info  50.13   
99       0  29.0             0              0         current  27.32   

    HbA1c_level  blood_glucose_level  diabetes  
0           6.6                  140         0  
1           6.6                   80         0  
2           5.7                  158         0  
3           5.0                  155         0  
4           4.8                  155         0  
..          ...                  ...       ...  
95          6.1                   80         0  
96          6.2                  159         1  
97          6.1                   90         0  
98          6.0                  100         0  
99          4.8                  158         0  

[100 rows x 9 columns]

In [8]:
x["gender"].unique()

array([1, 0, 2])

In [9]:
x["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [10]:
smoking_history_to_int = {'No Info' : 0, 'never': 1, 'current': 2, 'former': 3, 'ever' : 4, 'not current' : 5}
x['smoking_history'] = x['smoking_history'].map(smoking_history_to_int)

In [11]:
x["smoking_history"].unique()

array([1, 0, 2, 3, 4, 5])

In [12]:
x.head()

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0       1  80.0             0              1                1  25.19   
1       1  54.0             0              0                0  27.32   
2       0  28.0             0              0                1  27.32   
3       1  36.0             0              0                2  23.45   
4       0  76.0             1              1                2  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [13]:
x.loc[df['age'] < 15, 'smoking_history'] = 1

In [14]:
x.head(10000)

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0          1  80.0             0              1                1  25.19   
1          1  54.0             0              0                0  27.32   
2          0  28.0             0              0                1  27.32   
3          1  36.0             0              0                2  23.45   
4          0  76.0             1              1                2  20.14   
...      ...   ...           ...            ...              ...    ...   
9995       1   9.0             0              0                1  25.28   
9996       0  59.0             0              0                4  35.00   
9997       0   2.0             0              0                1  17.43   
9998       0  61.0             1              0                4  31.89   
9999       0  43.0             0              0                1  30.24   

      HbA1c_level  blood_glucose_level  diabetes  
0             6.6                  140         0  
1             6.6                   80         0  
2             5.7                  158         0  
3             5.0                  155         0  
4             4.8                  155         0  
...           ...                  ...       ...  
9995          5.8                  130         0  
9996          6.8                  140         1  
9997          4.5                  126         0  
9998          5.7                  140         0  
9999          6.6                  130         0  

[10000 rows x 9 columns]

In [15]:
x.pop("diabetes")

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

In [16]:
x.head()

gender   age  hypertension  heart_disease  smoking_history    bmi  \
0       1  80.0             0              1                1  25.19   
1       1  54.0             0              0                0  27.32   
2       0  28.0             0              0                1  27.32   
3       1  36.0             0              0                2  23.45   
4       0  76.0             1              1                2  20.14   

   HbA1c_level  blood_glucose_level  
0          6.6                  140  
1          6.6                   80  
2          5.7                  158  
3          5.0                  155  
4          4.8                  155

In [17]:


x_train, x_test, y_train, y_test = train_test_split(x,y, shuffle = True, stratify=y, train_size = 0.8)

In [18]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(8,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss = 'binary_crossentropy',
              optimizer = tf.keras.optimizers.Adam())

weights = {0: 1.0, 1: 5.0}
model.fit(x_train, y_train,epochs = 15, class_weight = weights)



Epoch 1/15
2500/2500 [==============================] - 10s 4ms/step - loss: 0.6925
Epoch 2/15
2500/2500 [==============================] - 12s 5ms/step - loss: 0.5026
Epoch 3/15
2500/2500 [==============================] - 6s 2ms/step - loss: 0.4072
Epoch 4/15
2500/2500 [==============================] - 6s 2ms/step - loss: 0.3681
Epoch 5/15
2500/2500 [==============================] - 5s 2ms/step - loss: 0.3471
Epoch 6/15
2500/2500 [==============================] - 7s 3ms/step - loss: 0.3345
Epoch 7/15
2500/2500 [==============================] - 5s 2ms/step - loss: 0.3254
Epoch 8/15
2500/2500 [==============================] - 5s 2ms/step - loss: 0.3161
Epoch 9/15
2500/2500 [==============================] - 6s 2ms/step - loss: 0.3104
Epoch 10/15
2500/2500 [==============================] - 5s 2ms/step - loss: 0.3138
Epoch 11/15
2500/2500 [==============================] - 6s 2ms/step - loss: 0.3029
Epoch 12/15
2500/2500 [==============================] - 5s 2ms/step - loss: 0.2977

In [19]:
y_train

46874    0
29947    0
12330    0
63126    0
26483    0
        ..
72651    0
69558    0
21408    1
42763    0
41261    0
Name: diabetes, Length: 80000, dtype: int64

In [20]:
y_pred = model.predict(x_test)

625/625 [==============================] - 1s 1ms/step


In [21]:
print(y_pred)

[[2.5873687e-02]
 [6.5865629e-06]
 [8.8481819e-03]
 ...
 [1.5222041e-01]
 [4.1116834e-02]
 [1.6437272e-03]]


In [22]:
a,b = 0,0 
for i in range(0,len(y_pred)):
     if y_pred[i] >= 0.3:
         y_pred[i] = 1
         a = a+1
         #print("True")
     else:
         y_pred[i] = 0
         #print("False")
         b += 1
print(a)
print(b)

3294
16706


In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.90      0.94     18300
           1       0.46      0.88      0.60      1700

    accuracy                           0.90     20000
   macro avg       0.72      0.89      0.77     20000
weighted avg       0.94      0.90      0.91     20000

