In [1]:
!pip install tensorflow
!pip install pandas
!pip install scikit-learn
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


In [2]:
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np
print("Import Done!")

2023-05-19 20:06:52.279225: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-19 20:06:53.076239: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-19 20:06:53.076319: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-05-19 20:06:53.197503: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-05-19 20:06:56.177206: W tensorflow/stream_executor/platform/de

Import Done!


In [3]:
df = pd.read_csv("diabetes_prediction_dataset.csv")

In [4]:
x = df.copy()
y = df["diabetes"].copy()

In [5]:
print(x.head())
print(y.head())

   gender   age  hypertension  heart_disease smoking_history    bmi   
0  Female  80.0             0              1           never  25.19  \
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0  
0    0
1    0
2    0
3    0
4    0
Name: diabetes, dtype: int64


In [6]:
x["gender"].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [7]:
gender_to_int = {'Male': 0, 'Female': 1, 'Other': 2}
x['gender'] = x['gender'].map(gender_to_int)

In [8]:
x.head(100)

gender   age  hypertension  heart_disease smoking_history    bmi   
0        1  80.0             0              1           never  25.19  \
1        1  54.0             0              0         No Info  27.32   
2        0  28.0             0              0           never  27.32   
3        1  36.0             0              0         current  23.45   
4        0  76.0             1              1         current  20.14   
..     ...   ...           ...            ...             ...    ...   
95       0  19.0             0              0           never  27.32   
96       1  67.0             0              0           never  27.32   
97       0  11.0             0              0         No Info  27.32   
98       1  30.0             0              0         No Info  50.13   
99       0  29.0             0              0         current  27.32   

    HbA1c_level  blood_glucose_level  diabetes  
0           6.6                  140         0  
1           6.6                   80         0  
2           5.7                  158         0  
3           5.0                  155         0  
4           4.8                  155         0  
..          ...                  ...       ...  
95          6.1                   80         0  
96          6.2                  159         1  
97          6.1                   90         0  
98          6.0                  100         0  
99          4.8                  158         0  

[100 rows x 9 columns]

In [9]:
x["gender"].unique()

array([1, 0, 2])

In [10]:
x["smoking_history"].unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [11]:
smoking_history_to_int = {'No Info' : 0, 'never': 1, 'current': 2, 'former': 3, 'ever' : 4, 'not current' : 5}
x['smoking_history'] = x['smoking_history'].map(smoking_history_to_int)

In [12]:
x["smoking_history"].unique()

array([1, 0, 2, 3, 4, 5])

In [13]:
x.head()

gender   age  hypertension  heart_disease  smoking_history    bmi   
0       1  80.0             0              1                1  25.19  \
1       1  54.0             0              0                0  27.32   
2       0  28.0             0              0                1  27.32   
3       1  36.0             0              0                2  23.45   
4       0  76.0             1              1                2  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [14]:
x.loc[df['age'] < 15, 'smoking_history'] = 1

In [15]:
x.head(10000)

gender   age  hypertension  heart_disease  smoking_history    bmi   
0          1  80.0             0              1                1  25.19  \
1          1  54.0             0              0                0  27.32   
2          0  28.0             0              0                1  27.32   
3          1  36.0             0              0                2  23.45   
4          0  76.0             1              1                2  20.14   
...      ...   ...           ...            ...              ...    ...   
9995       1   9.0             0              0                1  25.28   
9996       0  59.0             0              0                4  35.00   
9997       0   2.0             0              0                1  17.43   
9998       0  61.0             1              0                4  31.89   
9999       0  43.0             0              0                1  30.24   

      HbA1c_level  blood_glucose_level  diabetes  
0             6.6                  140         0  
1             6.6                   80         0  
2             5.7                  158         0  
3             5.0                  155         0  
4             4.8                  155         0  
...           ...                  ...       ...  
9995          5.8                  130         0  
9996          6.8                  140         1  
9997          4.5                  126         0  
9998          5.7                  140         0  
9999          6.6                  130         0  

[10000 rows x 9 columns]

In [16]:
x.pop("diabetes")

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

In [17]:
x.head()

gender   age  hypertension  heart_disease  smoking_history    bmi   
0       1  80.0             0              1                1  25.19  \
1       1  54.0             0              0                0  27.32   
2       0  28.0             0              0                1  27.32   
3       1  36.0             0              0                2  23.45   
4       0  76.0             1              1                2  20.14   

   HbA1c_level  blood_glucose_level  
0          6.6                  140  
1          6.6                   80  
2          5.7                  158  
3          5.0                  155  
4          4.8                  155

In [18]:


x_train, x_test, y_train, y_test = train_test_split(x,y, shuffle = True, stratify=y, train_size = 0.8)

In [19]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(8,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss = 'binary_crossentropy',
              optimizer = tf.keras.optimizers.Adam())

weights = {0: 1.0, 1: 5.0}
model.fit(x_train, y_train,epochs = 25, class_weight = weights)



2023-05-19 20:07:02.178728: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-05-19 20:07:02.179136: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2023-05-19 20:07:02.179225: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank): /proc/driver/nvidia/version does not exist
2023-05-19 20:07:02.180429: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Epoch 1/15
2500/2500 [==============================] - 13s 5ms/step - loss: 0.6443
Epoch 2/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.4801
Epoch 3/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.4033
Epoch 4/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.3635
Epoch 5/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.3420
Epoch 6/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.3300
Epoch 7/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.3237
Epoch 8/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.3170
Epoch 9/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.3087
Epoch 10/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.3083
Epoch 11/15
2500/2500 [==============================] - 11s 4ms/step - loss: 0.2979
Epoch 12/15
2500/2500 [==============================] - 12s 5ms/step - lo

In [20]:
y_train

65258    0
56330    0
31631    0
19943    0
23614    0
        ..
96226    0
52048    0
79325    0
11010    0
20776    0
Name: diabetes, Length: 80000, dtype: int64

In [21]:
y_pred = model.predict(x_test)

625/625 [==============================] - 2s 3ms/step


In [22]:
print(y_pred)

[[1.0188504e-01]
 [9.3422836e-01]
 [6.8872321e-01]
 ...
 [8.3516770e-06]
 [6.0377240e-01]
 [3.2227215e-01]]


In [23]:
a,b = 0,0 
for i in range(0,len(y_pred)):
     if y_pred[i] >= 0.3:
         y_pred[i] = 1
         a = a+1
         #print("True")
     else:
         y_pred[i] = 0
         #print("False")
         b += 1
print(a)
print(b)

3856
16144


In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.87      0.93     18300
           1       0.41      0.92      0.56      1700

    accuracy                           0.88     20000
   macro avg       0.70      0.90      0.75     20000
weighted avg       0.94      0.88      0.90     20000

